package tuigen

import (
	"strings"
	"testing"
)

func TestGenerator_SimpleComponent(t *testing.T) {
	type tc struct {
		input           string
		wantContains    []string
		wantNotContains []string
	}

	tests := map[string]tc{
		"empty component": {
			input: `package x
templ Empty() {
}`,
			wantContains: []string{
				"type EmptyView struct",
				"Root",
				"*tui.Element",
				"watchers",
				"[]tui.Watcher",
				"func Empty() *EmptyView",
				"var view EmptyView",
				"var watchers []tui.Watcher",
				"return &view",
			},
		},
		"component with single element": {
			input: `package x
templ Header() {
	<div></div>
}`,
			wantContains: []string{
				"type HeaderView struct",
				"func Header() *HeaderView",
				"__tui_0 := tui.New()",
				"Root:      __tui_0",
			},
		},
		"component with params": {
			input: `package x
templ Greeting(name string, count int) {
	<span>Hello</span>
}`,
			wantContains: []string{
				"func Greeting(name string, count int) *GreetingView",
				"type GreetingView struct",
			},
		},
		"component with grouped params": {
			input: `package x
templ Grp(x, y int, opts ...tui.Option) {
	<div options={opts}>{fmt.Sprint(x + y)}</div>
}`,
			wantContains: []string{
				"func Grp(x, y int, opts ...tui.Option) *GrpView",
				"fmt.Sprint(x + y)",
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}

			code := string(output)
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing expected string: %q\nGot:\n%s", want, code)
				}
			}
			for _, notWant := range tt.wantNotContains {
				if strings.Contains(code, notWant) {
					t.Errorf("output contains unexpected string: %q\nGot:\n%s", notWant, code)
				}
			}
		})
	}
}

func TestGenerator_NestedElements(t *testing.T) {
	input := `package x
templ Layout() {
	<div>
		<div>
			<span>nested</span>
		</div>
	</div>
}`

	output, err := parseAndGenerateSkipImports("test.gsx", input)
	if err != nil {
		t.Fatalf("generation failed: %v", err)
	}

	code := string(output)

	// Should have 3 element variables
	if !strings.Contains(code, "__tui_0 := tui.New()") {
		t.Error("missing outer box element")
	}

	// Should have AddChild calls
	if !strings.Contains(code, ".AddChild(") {
		t.Error("missing AddChild call")
	}

	// Should return view struct with Root set to outer element
	if !strings.Contains(code, "Root:      __tui_0") {
		t.Error("missing Root assignment to outer element")
	}

	if !strings.Contains(code, "return &view") {
		t.Error("missing return view statement")
	}
}

func TestGenerator_TopLevelGoFunc(t *testing.T) {
	input := `package x

func helper(x int) int {
	return x * 2
}

templ Test() {
	<span>hello</span>
}`

	output, err := parseAndGenerateSkipImports("test.gsx", input)
	if err != nil {
		t.Fatalf("generation failed: %v", err)
	}

	code := string(output)

	if !strings.Contains(code, "func helper(x int) int") {
		t.Errorf("missing helper function\nGot:\n%s", code)
	}

	if !strings.Contains(code, "return x * 2") {
		t.Errorf("missing helper function body\nGot:\n%s", code)
	}
}

func TestGenerator_ImportPropagation(t *testing.T) {
	input := `package x
import (
	"fmt"
	tui "github.com/grindlemire/go-tui"
)

templ Test() {
	<div direction={tui.Column}>
		<span>{fmt.Sprintf("hello")}</span>
	</div>
}`

	output, err := parseAndGenerateSkipImports("test.gsx", input)
	if err != nil {
		t.Fatalf("generation failed: %v", err)
	}

	code := string(output)

	// Original imports should be preserved
	if !strings.Contains(code, `"fmt"`) {
		t.Error("missing fmt import")
	}

	if !strings.Contains(code, `"github.com/grindlemire/go-tui"`) {
		t.Error("missing tui root import")
	}
}

func TestGenerator_Header(t *testing.T) {
	input := `package x
templ Test() {
	<span>hello</span>
}`

	output, err := parseAndGenerateSkipImports("test.gsx", input)
	if err != nil {
		t.Fatalf("generation failed: %v", err)
	}

	code := string(output)

	if !strings.Contains(code, "Code generated by tui generate. DO NOT EDIT.") {
		t.Error("missing DO NOT EDIT header")
	}

	if !strings.Contains(code, "Source: test.gsx") {
		t.Error("missing source file comment")
	}
}

func TestGenerator_MethodComponent(t *testing.T) {
	type tc struct {
		input           string
		wantContains    []string
		wantNotContains []string
	}

	tests := map[string]tc{
		"method templ generates method Render returning Element": {
			input: `package x

type sidebar struct{}

templ (s *sidebar) Render() {
	<div></div>
}`,
			wantContains: []string{
				"func (s *sidebar) Render(app *tui.App) *tui.Element {",
				"__tui_0 := tui.New()",
				"return __tui_0",
			},
			wantNotContains: []string{
				"View struct",
				"var view",
				"var watchers",
				"return &view",
			},
		},
		"method templ with nested elements": {
			input: `package x

type panel struct{}

templ (p *panel) Render() {
	<div class="flex-col">
		<span>hello</span>
	</div>
}`,
			wantContains: []string{
				"func (p *panel) Render(app *tui.App) *tui.Element {",
				"__tui_0 := tui.New(",
				"return __tui_0",
			},
			wantNotContains: []string{
				"PanelView",
				"var view",
			},
		},
		"method templ with struct mount": {
			input: `package x

type myApp struct{}

templ (a *myApp) Render() {
	<div>
		@Sidebar()
	</div>
}`,
			wantContains: []string{
				"func (a *myApp) Render(app *tui.App) *tui.Element {",
				"app.Mount(a, 0, func() tui.Component {",
				"return Sidebar()",
				"})",
				"__tui_0.AddChild(",
				"return __tui_0",
			},
			wantNotContains: []string{
				".Root",
				"var view",
			},
		},
		"mount indices increment for multiple mounts": {
			input: `package x

type myApp struct{}

templ (a *myApp) Render() {
	<div>
		@First()
		@Second()
		@Third()
	</div>
}`,
			wantContains: []string{
				"app.Mount(a, 0, func() tui.Component {",
				"return First()",
				"app.Mount(a, 1, func() tui.Component {",
				"return Second()",
				"app.Mount(a, 2, func() tui.Component {",
				"return Third()",
			},
		},
		"struct mount with args": {
			input: `package x

type myApp struct{}

templ (a *myApp) Render() {
	<div>
		@Sidebar(a.query)
		@SearchInput(a.active, a.query)
	</div>
}`,
			wantContains: []string{
				"app.Mount(a, 0, func() tui.Component {",
				"return Sidebar(a.query)",
				"app.Mount(a, 1, func() tui.Component {",
				"return SearchInput(a.active, a.query)",
			},
		},
		"method templ with conditional": {
			input: `package x

type sidebar struct{}

templ (s *sidebar) Render() {
	if true {
		<div><span>visible</span></div>
	}
}`,
			wantContains: []string{
				"func (s *sidebar) Render(app *tui.App) *tui.Element {",
				"if true {",
			},
		},
		"empty method templ returns nil": {
			input: `package x

type empty struct{}

templ (e *empty) Render() {
}`,
			wantContains: []string{
				"func (e *empty) Render(app *tui.App) *tui.Element {",
				"return nil",
			},
		},
		"method templ with struct mount as root returns element directly": {
			input: `package x

type app struct{}

templ (a *app) Render() {
	@Sidebar()
}`,
			wantContains: []string{
				"__tui_0 := app.Mount(a, 0, func() tui.Component {",
				"return __tui_0\n",
			},
			wantNotContains: []string{
				"__tui_0.Root",
			},
		},
		"method templ with function-component call as root returns .Root": {
			input: `package x

type app struct{}

templ Dashboard() {
	<div></div>
}

templ (a *app) Render() {
	@Dashboard()
}`,
			wantContains: []string{
				"func (a *app) Render(app *tui.App) *tui.Element {",
				"return __tui_0.Root",
			},
			wantNotContains: []string{
				"return __tui_0\n",
			},
		},
		"method templ with children slot uses receiver field": {
			input: `package x

type card struct {
	title    string
	children []*tui.Element
}

templ (c *card) Render() {
	<div>
		<span>{c.title}</span>
		{children...}
	</div>
}`,
			wantContains: []string{
				"for _, __child := range c.children {",
			},
			wantNotContains: []string{
				"range children {",
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}

			code := string(output)
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing expected string: %q\nGot:\n%s", want, code)
				}
			}
			for _, notWant := range tt.wantNotContains {
				if strings.Contains(code, notWant) {
					t.Errorf("output contains unexpected string: %q\nGot:\n%s", notWant, code)
				}
			}
		})
	}
}

func TestGenerator_FunctionTemplChildrenSlotUsesBareChildren(t *testing.T) {
	input := `package x

templ Card(title string) {
	<div>
		<span>{title}</span>
		{children...}
	</div>
}`

	output, err := parseAndGenerateSkipImports("test.gsx", input)
	if err != nil {
		t.Fatalf("generation failed: %v", err)
	}

	code := string(output)
	if !strings.Contains(code, "for _, __child := range children {") {
		t.Errorf("function templ should use bare 'children' parameter\nGot:\n%s", code)
	}
}

func TestGenerator_FunctionComponentCallUnchanged(t *testing.T) {
	type tc struct {
		input           string
		wantContains    []string
		wantNotContains []string
	}

	tests := map[string]tc{
		"function templ with component call uses view struct pattern": {
			input: `package x

templ Parent() {
	<div>
		@Header("title")
	</div>
}`,
			wantContains: []string{
				"func Parent() *ParentView",
				"type ParentView struct",
				`__tui_1 := Header("title")`,
				"__tui_0.AddChild(__tui_1.Root)",
				"return &view",
			},
			wantNotContains: []string{
				"tui.Mount",
				"func() tui.Component", // no mount factory closure
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}

			code := string(output)
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing expected string: %q\nGot:\n%s", want, code)
				}
			}
			for _, notWant := range tt.wantNotContains {
				if strings.Contains(code, notWant) {
					t.Errorf("output contains unexpected string: %q\nGot:\n%s", notWant, code)
				}
			}
		})
	}
}

func TestGenerator_VerbatimPassthrough(t *testing.T) {
	type tc struct {
		input           string
		wantContains    []string
		wantNotContains []string
	}

	tests := map[string]tc{
		"type definition passes through": {
			input: `package x

type sidebar struct {
	Query    string
	expanded bool
}

templ Header() {
	<span>hello</span>
}`,
			wantContains: []string{
				"type sidebar struct",
				"Query    string",
				"expanded bool",
				"func Header() *HeaderView",
			},
		},
		"constructor method passes through": {
			input: `package x

func (s *sidebar) toggle() {
	s.expanded = !s.expanded
}

templ Header() {
	<span>hello</span>
}`,
			wantContains: []string{
				"func (s *sidebar) toggle()",
				"s.expanded = !s.expanded",
			},
		},
		"simple var declaration passes through": {
			input: `package x

var defaultName = "hello"

templ Header() {
	<span>hello</span>
}`,
			wantContains: []string{
				`var defaultName = "hello"`,
			},
		},
		"const declaration passes through": {
			input: `package x

const maxItems = 10

templ Header() {
	<span>hello</span>
}`,
			wantContains: []string{
				"const maxItems = 10",
			},
		},
		"mixed file with type constructor method and templ": {
			input: `package x

type sidebar struct {
	expanded bool
}

func NewSidebar() *sidebar {
	return &sidebar{expanded: true}
}

func (s *sidebar) toggle() {
	s.expanded = !s.expanded
}

templ (s *sidebar) Render() {
	<div><span>sidebar</span></div>
}`,
			wantContains: []string{
				"type sidebar struct",
				"expanded bool",
				"func NewSidebar() *sidebar",
				"return &sidebar{expanded: true}",
				"func (s *sidebar) toggle()",
				"s.expanded = !s.expanded",
				"func (s *sidebar) Render(app *tui.App) *tui.Element",
				"return __tui_0",
			},
			wantNotContains: []string{
				"RenderView",
				"var view",
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}

			code := string(output)
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing expected string: %q\nGot:\n%s", want, code)
				}
			}
			for _, notWant := range tt.wantNotContains {
				if strings.Contains(code, notWant) {
					t.Errorf("output contains unexpected string: %q\nGot:\n%s", notWant, code)
				}
			}
		})
	}
}

func TestGenerator_ReactiveIf(t *testing.T) {
	type tc struct {
		input           string
		wantContains    []string
		wantNotContains []string
	}

	tests := map[string]tc{
		"reactive if with single state var": {
			input: `package x
templ Toggle() {
	count := tui.NewState(0)
	<div>
		if count.Get() == 0 {
			<span>{"zero"}</span>
		}
	</div>
}`,
			wantContains: []string{
				"__cond_0 := tui.New()",
				"__tui_0.AddChild(__cond_0)",
				"__update___cond_0 := func()",
				"__cond_0.RemoveAllChildren()",
				"if count.Get() == 0",
				"__update___cond_0()",
				`count.Bind(func(_ int) { __update___cond_0() })`,
			},
		},
		"reactive if/else": {
			input: `package x
templ Toggle() {
	count := tui.NewState(0)
	<div>
		if count.Get() >= 5 {
			<span>{"high"}</span>
		} else {
			<span>{"low"}</span>
		}
	</div>
}`,
			wantContains: []string{
				"__cond_0 := tui.New()",
				"__update___cond_0 := func()",
				"__cond_0.RemoveAllChildren()",
				"if count.Get() >= 5",
				"} else {",
				"__update___cond_0()",
				`count.Bind(func(_ int) { __update___cond_0() })`,
			},
		},
		"non-reactive if stays plain": {
			input: `package x
templ Static(show bool) {
	<div>
		if show {
			<span>{"visible"}</span>
		}
	</div>
}`,
			wantContains: []string{
				"if show {",
			},
			wantNotContains: []string{
				"__cond_",
				"RemoveAllChildren",
			},
		},
		"for loop with state in body becomes reactive": {
			input: `package x
templ LoopCond(items []string) {
	count := tui.NewState(0)
	<div>
		for _, item := range items {
			if count.Get() > 0 {
				<span>{item}</span>
			}
		}
	</div>
}`,
			wantContains: []string{
				"__loop_0_style := __tui_0.LayoutStyle()",
				"__loop_0 := tui.New(tui.WithDirection(__loop_0_style.Direction), tui.WithGap(__loop_0_style.Gap))",
				"RemoveAllChildren",
				"__update___loop_0 := func()",
				"__update___loop_0()",
				`count.Bind(func(_ int) { __update___loop_0() })`,
			},
			wantNotContains: []string{
				"__cond_", // if inside for stays non-reactive
			},
		},
		"for loop without state stays plain": {
			input: `package x
templ PlainLoop(items []string) {
	<div>
		for _, item := range items {
			<span>{item}</span>
		}
	</div>
}`,
			wantNotContains: []string{
				"__loop_",
				"__cond_",
				"RemoveAllChildren",
			},
		},
		"state in body also triggers binding": {
			input: `package x
import "fmt"
templ Multi() {
	count := tui.NewState(0)
	name := tui.NewState("hello")
	<div>
		if count.Get() > 0 {
			<span>{fmt.Sprintf("%s: %d", name.Get(), count.Get())}</span>
		}
	</div>
}`,
			wantContains: []string{
				"__cond_0 := tui.New()",
				`count.Bind(func(_ int) { __update___cond_0() })`,
				`name.Bind(func(_ string) { __update___cond_0() })`,
			},
		},
		"reactive for loop with component call resets views slice": {
			input: `package x
templ List() {
	count := tui.NewState(0)
	items := []string{"a", "b"}
	<div>
		for _, item := range items {
			if count.Get() > 0 {
				@Badge(item)
			}
		}
	</div>
}`,
			wantContains: []string{
				"var __tui_1_views []*BadgeView",
				"__tui_1_views = __tui_1_views[:0]",
				"RemoveAllChildren",
				"__tui_1_views = append(__tui_1_views, __tui_1)",
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}

			code := string(output)
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing expected string: %q\nGot:\n%s", want, code)
				}
			}
			for _, notWant := range tt.wantNotContains {
				if strings.Contains(code, notWant) {
					t.Errorf("output contains unexpected string: %q\nGot:\n%s", notWant, code)
				}
			}
		})
	}
}

func TestGenerator_MethodComponent_TopLevelIfProducesRoot(t *testing.T) {
	input := `package x
type panel struct {
	show *tui.State[bool]
}

templ (p *panel) Render() {
	if p.show.Get() {
		<span>{"on"}</span>
	} else {
		<span>{"off"}</span>
	}
}`

	output, err := parseAndGenerateSkipImports("test.gsx", input)
	if err != nil {
		t.Fatalf("generation failed: %v", err)
	}

	code := string(output)
	want := []string{
		"func (p *panel) Render(app *tui.App) *tui.Element {",
		"var __tui_0 *tui.Element",
		"if p.show.Get() {",
		"if __tui_0 == nil {",
		"__tui_0 = __tui_1",
		"__tui_0 = __tui_2",
		"return __tui_0",
	}
	for _, s := range want {
		if !strings.Contains(code, s) {
			t.Errorf("output missing expected string: %q\nGot:\n%s", s, code)
		}
	}

	if strings.Contains(code, "return nil") {
		t.Errorf("output contains unexpected return nil\nGot:\n%s", code)
	}
}

func TestGenerator_InputElement(t *testing.T) {
	type tc struct {
		input        string
		wantContains []string
	}

	tests := map[string]tc{
		"input generates mount with NewInput": {
			input: `package x

type myComp struct{}

templ (c *myComp) Render() {
	<input placeholder="Type here..." width={40} />
}`,
			wantContains: []string{
				"app.MountPersistent(",
				"tui.NewInput(",
				`tui.WithInputPlaceholder("Type here...")`,
				"tui.WithInputWidth(40)",
			},
		},
		"input with onSubmit handler": {
			input: `package x

type myComp struct{}

templ (c *myComp) Render() {
	<input onSubmit={c.handleSubmit} />
}`,
			wantContains: []string{
				"tui.NewInput(",
				"tui.WithInputOnSubmit(c.handleSubmit)",
			},
		},
		"input with border": {
			input: `package x

type myComp struct{}

templ (c *myComp) Render() {
	<input border={tui.BorderRounded} />
}`,
			wantContains: []string{
				"tui.NewInput(",
				"tui.WithInputBorder(tui.BorderRounded)",
			},
		},
		"input with individual borders": {
			input: `package x

type myComp struct{}

templ (c *myComp) Render() {
	<input borders={tui.BorderNone, tui.BorderNone, tui.BorderThick, tui.BorderNone} />
}`,
			wantContains: []string{
				"tui.NewInput(",
				"tui.WithInputBorderTRBL(tui.BorderNone, tui.BorderNone, tui.BorderThick, tui.BorderNone)",
			},
		},
		"input with no options": {
			input: `package x

type myComp struct{}

templ (c *myComp) Render() {
	<input />
}`,
			wantContains: []string{
				"app.MountPersistent(",
				"tui.NewInput()",
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}

			code := string(output)
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing %q.\nGot:\n%s", want, code)
				}
			}
		})
	}
}

func TestGenerator_TextareaElement(t *testing.T) {
	type tc struct {
		input        string
		wantContains []string
	}

	tests := map[string]tc{
		"textarea generates mount with NewTextArea": {
			input: `package x

type myComp struct{}

templ (c *myComp) Render() {
	<textarea placeholder="Type here..." width={40} />
}`,
			wantContains: []string{
				"app.MountPersistent(",
				"tui.NewTextArea(",
				`tui.WithTextAreaPlaceholder("Type here...")`,
				"tui.WithTextAreaWidth(40)",
			},
		},
		"textarea with onSubmit handler": {
			input: `package x

type myComp struct{}

templ (c *myComp) Render() {
	<textarea onSubmit={c.handleSubmit} />
}`,
			wantContains: []string{
				"tui.NewTextArea(",
				"tui.WithTextAreaOnSubmit(c.handleSubmit)",
			},
		},
		"textarea with border": {
			input: `package x

type myComp struct{}

templ (c *myComp) Render() {
	<textarea border={tui.BorderRounded} />
}`,
			wantContains: []string{
				"tui.NewTextArea(",
				"tui.WithTextAreaBorder(tui.BorderRounded)",
			},
		},
		"textarea with individual borders": {
			input: `package x

type myComp struct{}

templ (c *myComp) Render() {
	<textarea borders={tui.BorderNone, tui.BorderThick, tui.BorderThick, tui.BorderNone} />
}`,
			wantContains: []string{
				"tui.NewTextArea(",
				"tui.WithTextAreaBorderTRBL(tui.BorderNone, tui.BorderThick, tui.BorderThick, tui.BorderNone)",
			},
		},
		"textarea with no options": {
			input: `package x

type myComp struct{}

templ (c *myComp) Render() {
	<textarea />
}`,
			wantContains: []string{
				"app.MountPersistent(",
				"tui.NewTextArea()",
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}

			code := string(output)
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing %q.\nGot:\n%s", want, code)
				}
			}
		})
	}
}

func TestGenerator_MarkdownElement(t *testing.T) {
	type tc struct {
		input        string
		wantContains []string
	}

	tests := map[string]tc{
		"markdown source attr": {
			input: `package x

type myComp struct{}

templ (c *myComp) Render() {
	<markdown source={c.readme} width={80} />
}`,
			wantContains: []string{
				"app.MountPersistent(",
				"tui.NewMarkdown(",
				"tui.WithMarkdownSource(c.readme)",
				"tui.WithMarkdownWidth(80)",
			},
		},
		"markdown state attr": {
			input: `package x

type myComp struct{}

templ (c *myComp) Render() {
	<markdown state={c.md} />
}`,
			wantContains: []string{
				"tui.NewMarkdown(",
				"tui.WithMarkdownState(c.md)",
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}

			code := string(output)
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing %q.\nGot:\n%s", want, code)
				}
			}
		})
	}
}

func TestGenerator_InterfaceChecks(t *testing.T) {
	type tc struct {
		input           string
		wantContains    []string
		wantNotContains []string
	}

	tests := map[string]tc{
		"KeyMap method emits KeyListener check": {
			input: `package x

type counter struct{}

templ (c *counter) Render() {
	<div>hello</div>
}

func (c *counter) KeyMap() tui.KeyMap {
	return nil
}`,
			wantContains: []string{
				"_ tui.KeyListener = (*counter)(nil)",
			},
		},
		"HandleMouse method emits MouseListener check": {
			input: `package x

type clicker struct{}

templ (c *clicker) Render() {
	<div>hello</div>
}

func (c *clicker) HandleMouse(me tui.MouseEvent) bool {
	return false
}`,
			wantContains: []string{
				"_ tui.MouseListener = (*clicker)(nil)",
			},
		},
		"Init method emits Initializer check": {
			input: `package x

type loader struct{}

templ (l *loader) Render() {
	<div>hello</div>
}

func (l *loader) Init() func() {
	return nil
}`,
			wantContains: []string{
				"_ tui.Initializer = (*loader)(nil)",
			},
		},
		"Watchers method emits WatcherProvider check": {
			input: `package x

type ticker struct{}

templ (t *ticker) Render() {
	<div>hello</div>
}

func (t *ticker) Watchers() []tui.Watcher {
	return nil
}`,
			wantContains: []string{
				"_ tui.WatcherProvider = (*ticker)(nil)",
			},
		},
		"multiple interfaces on same type": {
			input: `package x

type app struct{}

templ (a *app) Render() {
	<div>hello</div>
}

func (a *app) KeyMap() tui.KeyMap {
	return nil
}

func (a *app) Init() func() {
	return nil
}`,
			wantContains: []string{
				"_ tui.KeyListener = (*app)(nil)",
				"_ tui.Initializer = (*app)(nil)",
			},
		},
		"no checks for function components": {
			input: `package x

templ Header() {
	<div>hello</div>
}

func helper() {}`,
			wantNotContains: []string{
				"Compile-time interface",
			},
		},
		"no checks for non-component receiver types": {
			input: `package x

type helper struct{}

templ Header() {
	<div>hello</div>
}

func (h *helper) KeyMap() tui.KeyMap {
	return nil
}`,
			wantNotContains: []string{
				"_ tui.KeyListener",
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}

			code := string(output)
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing expected string: %q\nGot:\n%s", want, code)
				}
			}
			for _, notWant := range tt.wantNotContains {
				if strings.Contains(code, notWant) {
					t.Errorf("output contains unexpected string: %q\nGot:\n%s", notWant, code)
				}
			}
		})
	}
}

func TestGenerator_ConditionalComponentCallScoping(t *testing.T) {
	type tc struct {
		input           string
		wantContains    []string
		wantNotContains []string
	}

	tests := map[string]tc{
		"component call inside if block hoists var and nil-guards wiring": {
			input: `package x

templ ItemRow(hasBadge bool) {
	<div>
		<span>name</span>
		if hasBadge {
			@Badge()
		}
	</div>
}`,
			wantContains: []string{
				// Hoisted declaration at function scope
				"var __tui_2 *BadgeView",
				// Assignment (not short declaration) inside the if block
				"__tui_2 = Badge()",
				// Nil-guarded watcher aggregation
				"if __tui_2 != nil {\n\t\twatchers = append(watchers, __tui_2.GetWatchers()...)\n\t}",
				// Nil-guarded bindApp (3 tabs: function body > closure body > nil guard)
				"if __tui_2 != nil {\n\t\t\tif binder, ok := any(__tui_2).(tui.AppBinder)",
				// Nil-guarded unbindApp
				"if __tui_2 != nil {\n\t\t\tif unbinder, ok := any(__tui_2).(tui.AppUnbinder)",
			},
			wantNotContains: []string{
				// Must NOT have short declaration inside the if block
				"__tui_2 := Badge()",
			},
		},
		"unconditional component call is unchanged": {
			input: `package x

templ Parent() {
	<div>
		@Header()
	</div>
}`,
			wantContains: []string{
				"__tui_1 := Header()",
				"watchers = append(watchers, __tui_1.GetWatchers()...)",
			},
			wantNotContains: []string{
				"var __tui_1",
				"if __tui_1 != nil",
			},
		},
		"mixed conditional and unconditional component calls": {
			input: `package x

templ Mixed(show bool) {
	<div>
		@Header()
		if show {
			@Badge()
		}
	</div>
}`,
			wantContains: []string{
				// Header is unconditional
				"__tui_1 := Header()",
				// Badge is conditional — hoisted
				"var __tui_2 *BadgeView",
				"__tui_2 = Badge()",
				// Header watcher is direct
				"watchers = append(watchers, __tui_1.GetWatchers()...)",
				// Badge watcher is nil-guarded
				"if __tui_2 != nil {\n\t\twatchers = append(watchers, __tui_2.GetWatchers()...)\n\t}",
			},
		},
		"component calls in both if and else branches": {
			input: `package x

templ Row(a bool) {
	<div>
		if a {
			@Badge()
		} else {
			@Icon()
		}
	</div>
}`,
			wantContains: []string{
				"var __tui_1 *BadgeView",
				"var __tui_2 *IconView",
				"__tui_1 = Badge()",
				"__tui_2 = Icon()",
				"if __tui_1 != nil",
				"if __tui_2 != nil",
			},
			wantNotContains: []string{
				"__tui_1 := Badge()",
				"__tui_2 := Icon()",
			},
		},
		"nested conditional component call": {
			input: `package x

templ Nested(a bool, b bool) {
	<div>
		if a {
			if b {
				@Badge()
			}
		}
	</div>
}`,
			wantContains: []string{
				"var __tui_1 *BadgeView",
				"__tui_1 = Badge()",
				"if __tui_1 != nil",
			},
			wantNotContains: []string{
				"__tui_1 := Badge()",
			},
		},
		"component call in children-building if block": {
			input: `package x

templ Outer(show bool) {
	<div>
		@Wrapper() {
			if show {
				@Badge()
			}
		}
	</div>
}`,
			wantContains: []string{
				// __tui_3 because __tui_2 is consumed by the children slice variable
				"var __tui_3 *BadgeView",
				"__tui_3 = Badge()",
				"if __tui_3 != nil",
			},
			wantNotContains: []string{
				"__tui_3 := Badge()",
			},
		},
		"component call inside for loop collects views slice": {
			input: `package x

templ List(items []string) {
	<div>
		for _, item := range items {
			@Badge(item)
		}
	</div>
}`,
			wantContains: []string{
				"var __tui_1_views []*BadgeView",
				"__tui_1 := Badge(item)",
				"__tui_1_views = append(__tui_1_views, __tui_1)",
				"for _, __cv := range __tui_1_views",
				"watchers = append(watchers, __cv.GetWatchers()...)",
			},
			wantNotContains: []string{
				"var __tui_1 *BadgeView",
				"__tui_1 = Badge(item)",
				"if __tui_1 != nil",
			},
		},
		"component call inside if inside for loop uses views slice": {
			input: `package x

templ List(items []string) {
	<div>
		for _, item := range items {
			if item != "" {
				@Badge(item)
			}
		}
	</div>
}`,
			wantContains: []string{
				"var __tui_1_views []*BadgeView",
				"__tui_1 := Badge(item)",
				"__tui_1_views = append(__tui_1_views, __tui_1)",
				"for _, __cv := range __tui_1_views",
			},
			wantNotContains: []string{
				"var __tui_1 *BadgeView",
			},
		},
		"mixed: component call outside and inside for loop": {
			input: `package x

templ Mixed(items []string) {
	<div>
		@Header()
		for _, item := range items {
			@Badge(item)
		}
	</div>
}`,
			wantContains: []string{
				// Outside the loop: normal single-var pattern
				"__tui_1 := Header()",
				"watchers = append(watchers, __tui_1.GetWatchers()...)",
				// Inside the loop: views slice pattern
				"var __tui_2_views []*BadgeView",
				"__tui_2 := Badge(item)",
				"__tui_2_views = append(__tui_2_views, __tui_2)",
				"for _, __cv := range __tui_2_views",
			},
			wantNotContains: []string{
				// Outside call should NOT get slice treatment
				"__tui_1_views",
				// Inside call should NOT get single-var hoist
				"var __tui_2 *BadgeView",
			},
		},
		"method templ with conditional function templ uses short declaration": {
			input: `package x

type sidebar struct{}

templ Foo() {
	<div></div>
}

templ (s *sidebar) Render() {
	<div>
		if true {
			@Foo()
		}
	</div>
}`,
			wantContains: []string{
				// Method templs don't hoist - they use := inside the block
				"__tui_1 := Foo()",
			},
			wantNotContains: []string{
				// No hoisted var declaration
				"var __tui_1",
				// No bare assignment
				"__tui_1 = Foo()",
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}

			code := string(output)
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing expected string: %q\nGot:\n%s", want, code)
				}
			}
			for _, notWant := range tt.wantNotContains {
				if strings.Contains(code, notWant) {
					t.Errorf("output contains unexpected string: %q\nGot:\n%s", notWant, code)
				}
			}
		})
	}
}

// TestGenerator_UserBindAppDoesNotSuppressUnbindApp verifies the fix for a
// generator bug where a user-defined BindApp (via hasUserBindAppMethod) also
// suppressed auto-generation of UnbindApp, leaving components that owned
// Events subscriptions unable to satisfy AppUnbinder and leaking their
// subscriptions across root resets.
func TestGenerator_UserBindAppDoesNotSuppressUnbindApp(t *testing.T) {
	input := `package x

import tui "github.com/grindlemire/go-tui"

type myRoot struct {
	app    *tui.App
	events *tui.Events[string]
}

func (c *myRoot) BindApp(app *tui.App) {
	c.app = app
	c.bindAppFields(app)
}

templ (c *myRoot) Render() {
	<div></div>
}
`

	output, err := parseAndGenerateSkipImports("test.gsx", input)
	if err != nil {
		t.Fatalf("generation failed: %v", err)
	}
	code := string(output)

	mustContain := []string{
		"func (c *myRoot) unbindAppFields()",
		"func (c *myRoot) UnbindApp()",
		"c.unbindAppFields()",
		"var _ tui.AppUnbinder = (*myRoot)(nil)",
	}
	for _, want := range mustContain {
		if !strings.Contains(code, want) {
			t.Errorf("output missing expected string: %q\nGot:\n%s", want, code)
		}
	}
}

// TestGenerator_UpdatePropsReceiverShadowing verifies that the generated
// UpdateProps does not shadow the method receiver with the type-asserted
// local. When a component's receiver was named "f" (the hardcoded local
// name), the assertion shadowed the receiver and every prop copy became a
// self-assignment, silently dropping prop updates on cached components.
func TestGenerator_UpdatePropsReceiverShadowing(t *testing.T) {
	type tc struct {
		input           string
		wantContains    []string
		wantNotContains []string
	}

	tests := map[string]tc{
		"receiver named f does not shadow the fresh local": {
			input: `package x

type fileList struct {
	files []string
}

templ (f *fileList) Render() {
	<div></div>
}`,
			wantContains: []string{
				"func (f *fileList) UpdateProps(fresh tui.Component) {",
				"f.files = ff.files",
			},
			wantNotContains: []string{
				"f.files = f.files",
			},
		},
		"non-colliding receiver keeps the f local": {
			input: `package x

type fileList struct {
	files []string
}

templ (l *fileList) Render() {
	<div></div>
}`,
			wantContains: []string{
				"f, ok := fresh.(*fileList)",
				"l.files = f.files",
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}

			code := string(output)
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing expected string: %q\nGot:\n%s", want, code)
				}
			}
			for _, notWant := range tt.wantNotContains {
				if strings.Contains(code, notWant) {
					t.Errorf("output contains unexpected string: %q\nGot:\n%s", notWant, code)
				}
			}
		})
	}
}

// TestGenerator_PackageContextSuppressesLifecycleMethods verifies that a
// lifecycle method declared in a sibling file of the package (via
// PackageContext) suppresses the generated wrapper, the same as a
// declaration in the .gsx file itself.
func TestGenerator_PackageContextSuppressesLifecycleMethods(t *testing.T) {
	input := `package x

import tui "github.com/grindlemire/go-tui"

type row struct {
	value  string
	events *tui.Events[string]
}

templ (r *row) Render() {
	<span>{r.value}</span>
}
`
	sibling := `package x

import tui "github.com/grindlemire/go-tui"

func (r *row) UpdateProps(fresh tui.Component) {
	r.updatePropsFields(fresh)
}

func (r *row) UnbindApp() {
	r.unbindAppFields()
}
`

	lexer := NewLexer("test.gsx", input)
	parser := NewParser(lexer)
	file, err := parser.ParseFile()
	if err != nil {
		t.Fatalf("parse failed: %v", err)
	}

	ctx := NewPackageContext()
	if err := ctx.AddGoSource("sibling.go", sibling); err != nil {
		t.Fatalf("AddGoSource failed: %v", err)
	}

	gen := NewGenerator()
	gen.SkipImports = true
	gen.SetPackageContext(ctx)
	output, err := gen.Generate(file, "test.gsx")
	if err != nil {
		t.Fatalf("generation failed: %v", err)
	}
	code := string(output)

	if strings.Contains(code, "func (r *row) UpdateProps(") {
		t.Errorf("generated UpdateProps despite sibling declaration\nGot:\n%s", code)
	}
	if strings.Contains(code, "func (r *row) UnbindApp(") {
		t.Errorf("generated UnbindApp despite sibling declaration\nGot:\n%s", code)
	}
	// BindApp has no sibling declaration, so it is still generated, and the
	// delegation helpers are always emitted.
	for _, want := range []string{
		"func (r *row) BindApp(app *tui.App) {",
		"func (r *row) updatePropsFields(fresh tui.Component) {",
		"func (r *row) unbindAppFields() {",
	} {
		if !strings.Contains(code, want) {
			t.Errorf("output missing expected string: %q\nGot:\n%s", want, code)
		}
	}
}

// TestHasUserMethod verifies user-method detection across the receiver forms
// Go allows. Unnamed receivers are legal and must be detected, or the
// generator emits a duplicate lifecycle method.
func TestHasUserMethod(t *testing.T) {
	type tc struct {
		code string
		want bool
	}

	tests := map[string]tc{
		"named pointer receiver": {
			code: "func (r *row) UpdateProps(fresh tui.Component) {}",
			want: true,
		},
		"named value receiver": {
			code: "func (r row) UpdateProps(fresh tui.Component) {}",
			want: true,
		},
		"unnamed pointer receiver": {
			code: "func (*row) UpdateProps(fresh tui.Component) {}",
			want: true,
		},
		"unnamed value receiver": {
			code: "func (row) UpdateProps(fresh tui.Component) {}",
			want: true,
		},
		"method on another type": {
			code: "func (r *other) UpdateProps(fresh tui.Component) {}",
			want: false,
		},
		"type name is a prefix of another type": {
			code: "func (r *rowExtra) UpdateProps(fresh tui.Component) {}",
			want: false,
		},
		"plain function with the method name": {
			code: "func UpdateProps(fresh tui.Component) {}",
			want: false,
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			funcs := []*GoFunc{{Code: tt.code}}
			if got := hasUserMethod(nil, funcs, "*row", "UpdateProps"); got != tt.want {
				t.Errorf("hasUserMethod(%q) = %v, want %v", tt.code, got, tt.want)
			}
		})
	}
}

// TestGenerator_UserUpdatePropsSuppressesGenerated verifies that a
// user-defined UpdateProps on the receiver type suppresses the generated
// wrapper. Without the check, the generator emitted a second UpdateProps and
// Go rejected the package with a duplicate-method error. The unexported
// updatePropsFields helper is always emitted so overrides can delegate to it.
func TestGenerator_UserUpdatePropsSuppressesGenerated(t *testing.T) {
	type tc struct {
		input           string
		wantCount       map[string]int
		wantContains    []string
		wantNotContains []string
	}

	tests := map[string]tc{
		"user-defined UpdateProps suppresses the generated wrapper": {
			input: `package x

import tui "github.com/grindlemire/go-tui"

type lifecycleRow struct {
	value string
}

func (r *lifecycleRow) UpdateProps(fresh tui.Component) {
	r.updatePropsFields(fresh)
}

templ (r *lifecycleRow) Render() {
	<span>{r.value}</span>
}`,
			// The user's own method passes through to the output; the
			// generator must not add a second one.
			wantCount: map[string]int{
				"func (r *lifecycleRow) UpdateProps(": 1,
			},
			wantContains: []string{
				"func (r *lifecycleRow) updatePropsFields(fresh tui.Component) {",
				"r.value = f.value",
				// The assertion is still emitted so a wrong-signature user
				// UpdateProps fails loudly instead of silently dropping
				// prop refresh on cached components.
				"var _ tui.PropsUpdater = (*lifecycleRow)(nil)",
			},
		},
		"no user method generates wrapper delegating to helper": {
			input: `package x

type lifecycleRow struct {
	value string
}

templ (r *lifecycleRow) Render() {
	<span>{r.value}</span>
}`,
			wantCount: map[string]int{
				"func (r *lifecycleRow) UpdateProps(": 1,
			},
			wantContains: []string{
				"func (r *lifecycleRow) updatePropsFields(fresh tui.Component) {",
				"r.updatePropsFields(fresh)",
				"var _ tui.PropsUpdater = (*lifecycleRow)(nil)",
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}
			code := string(output)

			for substr, want := range tt.wantCount {
				if got := strings.Count(code, substr); got != want {
					t.Errorf("substring %q appears %d times, want %d\nGot:\n%s", substr, got, want, code)
				}
			}
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing expected string: %q\nGot:\n%s", want, code)
				}
			}
			for _, notWant := range tt.wantNotContains {
				if strings.Contains(code, notWant) {
					t.Errorf("output contains unexpected string: %q\nGot:\n%s", notWant, code)
				}
			}
		})
	}
}

func TestGenerator_QualifiedComponentCall(t *testing.T) {
	type tc struct {
		input           string
		wantContains    []string
		wantNotContains []string
	}

	tests := map[string]tc{
		"function templ calls the qualified function and uses .Root": {
			input: `package x

import "example.com/app/widgets"

templ Parent() {
	<div>
		@widgets.Header("hi")
	</div>
}`,
			wantContains: []string{
				`__tui_1 := widgets.Header("hi")`,
				"__tui_0.AddChild(__tui_1.Root)",
			},
			wantNotContains: []string{
				"widgets.Header.Render",
				`tui.WithText("(")`,
			},
		},
		"method templ mounts the qualified factory": {
			input: `package x

import "example.com/app/widgets"

type Root struct{}

templ (r *Root) Render() {
	<div>
		@widgets.NewCard("hi")
	</div>
}`,
			wantContains: []string{
				"app.Mount(r, 0, func() tui.Component {",
				`return widgets.NewCard("hi")`,
			},
			wantNotContains: []string{
				"widgets.NewCard.Render",
			},
		},
		"qualified call in let binding": {
			input: `package x

import "example.com/app/widgets"

templ Parent() {
	h := @widgets.Header("hi")
	<div>{h}</div>
}`,
			wantContains: []string{
				`widgets.Header("hi")`,
			},
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			output, err := parseAndGenerateSkipImports("test.gsx", tt.input)
			if err != nil {
				t.Fatalf("generation failed: %v", err)
			}
			code := string(output)
			for _, want := range tt.wantContains {
				if !strings.Contains(code, want) {
					t.Errorf("output missing expected string: %q\nGot:\n%s", want, code)
				}
			}
			for _, notWant := range tt.wantNotContains {
				if strings.Contains(code, notWant) {
					t.Errorf("output contains unexpected string: %q\nGot:\n%s", notWant, code)
				}
			}
		})
	}
}
